#运行模式
[Runmode]
Runmode="dev"
#production
[pro]
#redis配置
RedisHost="192.168.199.248"
RedisPort="6379"
RedisPassword=""
RedisDB=0
Redis=true
#DB配置
DBHost="192.168.199.248"
DBPort="3306"
DBUsername="root"
DBPassword="mysql123456"
DBName="blog"
DB=true

#develop
[dev]
#redis配置
RedisHost="192.168.199.248"
RedisPort="6379"
RedisPassword=""
RedisDB=0
Redis=false
#DB配置
DBHost="192.168.199.248"
DBPort="3306"
DBUsername="root"
DBPassword="mysql123456"
DBName="blog"
DB=true
